        {"Dog bed","You sleep for an hour"},
        {"Big bed","You sleep for an hour"},
        {"Front door","You bark at the front door"},
        {"TV","There is no dog on the TV"},
        {"Water bowl","Slurp Slurp Slurp Slurp Slurp"},
        {"Food bowl","You bark at the empty bowl"},
        {"Food bowl","Chomp Chomp Chomp Chomp Chomp"},
        {"Laundry basket","You find a sock"},
        {"Put down socks","You put down the socks"},
        {"Socks","You pick up the socks"},
        {"Ball","You pick up the ball"},
        {"Put down ball","You drop the ball"},
