        {"Bedroom","A cosy bedroom with a big bed and a dog bed"},
        {"Hallway","A long hallway with a hard wood floor"},
        {"Street","Terraced houses go along the steep street"},
        {"Living room","A room with a big sofa. There’s a dog bed on the floor and a tv on the wall"},
        {"Kitchen","Lot’s of food on the sides. There’s two dog bowls on the floor"},
        {"Study","Two desks with computers and a big comfy sofa"},
        {"Little park","A small park with lots of climbing frames"},
        {"Big park","A large park with trees and hills"},
        {"Forest","A forest with lots of fallen down trees and muddy patches"},
        {"Green","An old bowling green"},
        {"Armstrong park","A long park with a few different paths through"},
        {"Jesmond dene","A long park with a river running through it"},
